#!/usr/bin/env python
# Author: Xi Yang
# Figures 1-4: regenerated end-to-end from the single unified statistics engine
# (recompute_statistics.R -> build_tables.py). Fix history preserved from the
# development series (kept as documentation, not code to re-derive):
#  - GSE19760 array weight-averaging bug (avereps on weights, not first-probe)
#  - Hpx-/GSE165009 OxyR gene-set score no longer silently includes the
#    genotype-deleted genes ahpC/katG (Methods now matches code)
#  - stale "gorA" alias replaced by canonical symbol "gor" everywhere
#  - Fig1C/Fig4 read exclusively from the statistics-engine outputs below --
#    no file in this script touches any pre-fix intermediate.
#  - roast() requires strictly positive precision weight for every array in the
#    tested index; gene sets are reported at their roast-tested size (n_genes),
#    with the full accounting (not-measured vs partial-weight-excluded genes)
#    in Table S2, not silently absorbed into the figure.
# Figure 5 (conservation) is generated by the separate make_fig5_conservation.py,
# which shares the same --fig-out directory, so exactly one script per figure.
import argparse
import os
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
matplotlib.rcParams["font.family"] = ["Liberation Sans", "Arimo", "DejaVu Sans"]
matplotlib.rcParams["svg.fonttype"] = "none"
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from adjustText import adjust_text
from scipy.stats import fisher_exact


def main(stats, final, data, fig_out):
    global FIG
    FIG = fig_out
    os.makedirs(FIG, exist_ok=True)
    STATS, FINAL, DATA = stats, final, data

    # ---------- shared data (all from the v4 statistics engine / build_tables.py) ----------
    ft = pd.read_csv(f"{DATA}/mg1655_feature_table.txt.gz", sep="\t",
                     compression="gzip", low_memory=False)
    ft = ft.rename(columns={ft.columns[0]: "feature"})

    de = pd.read_csv(f"{STATS}/DE_Reuterin.csv")  # already has symbol, bnum, logFC, AveExpr, adj.P.Val

    uni = pd.read_csv(f"{STATS}/genesets_primary.csv")  # contrast, gene_set, n_genes, raw_mean_logFC, roast_q_up, ...

    M = pd.read_csv(f"{STATS}/M_Reuterin.csv").set_index("symbol")
    M = M[["rep1", "rep2", "rep3", "rep4", "rep5"]]

    t1 = pd.read_csv(f"{FINAL}/supplementary/Table_S1_CLASH_interactions_v4.csv")

    CONTRAST_LABEL = {"Reuterin": "Reuterin (GSE19760)", "Hpx": "Hpx$^-$ H$_2$O$_2$ (GSE165009)",
                      "HOCl": "HOCl K-12 (GSE126176)", "Ferrate": "Ferrate K-12 (GSE126176)"}
    CONTRASTS = ["Reuterin", "Hpx", "HOCl", "Ferrate"]

    # frozen gene sets used by the v4 statistics engine (recompute_statistics.R SETS list);
    # "gor" replaces the stale "gorA" alias (gorA is a synonym for gor / b3500, NCBI/EcoCyc).
    GENE_SETS = {
     "ISC operon": ["iscR", "iscS", "iscU", "iscA", "hscB", "hscA", "fdx"],
     "SUF operon": ["sufA", "sufB", "sufC", "sufD", "sufS", "sufE"],
     "RyhB targets": ["sodB", "fumA", "acnA", "sdhC", "sdhD", "sdhA", "sdhB", "bfr", "ftnA",
                      "iscS", "iscU", "iscA"],
     "Fur iron uptake": ["fhuA", "fhuE", "fhuF", "fecA", "fepA", "fepB", "entC", "entB", "entE",
                         "fes", "cirA", "fiu", "tonB", "exbB", "exbD"],
     "OxyR regulon": ["ahpC", "ahpF", "katG", "dps", "grxA", "trxC", "gor", "fur",
                      "sufA", "sufB", "sufC", "sufD", "sufS", "sufE"],
     "Cysteine regulon": ["cysK", "cysM", "cysE", "cysA", "cysW", "cysU", "cysJ", "cysI", "cysH",
                     "cysD", "cysN", "cysC", "cysP", "sbp"],
     "Glutathione/glyoxalase": ["gshA", "gshB", "gor", "ggt", "gloA", "gloB", "gloC", "yajG", "grxA", "grxB"],
     "Electrophile detoxification": ["nemA", "nemR", "yqhD", "yqhC", "dkgA", "dkgB"],
    }
    # 86-gene sulfur universe for network colouring (Table S1 target_pathway) -- from
    # enrichment_sensitivity.py / build_tables.py PATHWAYS; a separate, Python-side curated
    # list from the R gene sets above (e.g. includes cysB, which the R "Cysteine regulon" does not).
    sulfur_genes = {
     "iscRSUA_operon": ["iscR", "iscS", "iscU", "iscA", "hscB", "hscA", "fdx"],
     "suf_operon": ["sufA", "sufB", "sufC", "sufD", "sufS", "sufE"],
     "cys_regulon": ["cysK", "cysM", "cysE", "cysA", "cysW", "cysU", "cysJ", "cysI", "cysH",
                     "cysD", "cysN", "cysC", "cysP", "sbp", "cysB"],
     "GSH_glyoxalase": ["gshA", "gshB", "gor", "ggt", "gloA", "gloB", "gloC", "yajG", "grxA",
                        "grxB", "grxC", "grxD", "trxA", "trxB", "trxC"],
     "electrophile_detox": ["nemA", "nemR", "yqhD", "yqhC", "dkgA", "dkgB", "ahr", "ydgI",
                            "yafC", "yqhE"],
     "FeS_iron": ["fur", "ryhB", "sodB", "fumA", "acnA", "acnB", "sdhC", "sdhD", "sdhA", "sdhB",
                  "bfr", "ftnA", "ftnB", "nfuA", "erpA", "yggX"],
     "H2S_taurine": ["tauA", "tauB", "tauC", "tauD", "ssuA", "ssuB", "ssuC", "ssuD", "ssuE",
                     "metA", "metB", "metC", "metE", "metH", "metF", "metK", "metL"],
    }
    pathway_colors = {"iscRSUA_operon": "#D55E00", "suf_operon": "#E69F00", "cys_regulon": "#009E73",
                      "GSH_glyoxalase": "#0072B2", "electrophile_detox": "#CC79A7",
                      "FeS_iron": "#999999", "H2S_taurine": "#56B4E9"}
    pathway_labels = {"iscRSUA_operon": "ISC Fe-S biogenesis", "suf_operon": "SUF Fe-S biogenesis",
                      "cys_regulon": "Cysteine regulon", "GSH_glyoxalase": "Glutathione/glyoxalase",
                      "electrophile_detox": "Electrophile detox", "FeS_iron": "Iron/Fe-S homeostasis",
                      "H2S_taurine": "S-assimilation/Met"}

    def stars_q(q):
        return "***" if q < 0.001 else ("**" if q < 0.01 else ("*" if q < 0.05 else ""))

    def save(fig, name):
        fig.savefig(f"{FIG}/{name}.png", dpi=300, bbox_inches="tight")
        fig.savefig(f"{FIG}/{name}.svg", bbox_inches="tight")
        plt.close(fig)
        print("saved", name)

    # =====================================================================
    # FIGURE 1 v4: volcano + MA + gene-set bars (roast, v4 statistics engine)
    # =====================================================================
    fig, axes = plt.subplots(1, 3, figsize=(16.5, 4.9))
    dev = de.dropna(subset=["adj.P.Val"])
    x = dev.logFC.values
    y = -np.log10(dev["adj.P.Val"].clip(lower=1e-10)).values
    sig = (dev["adj.P.Val"] < 0.05).values

    ax = axes[0]
    ax.scatter(x[~sig], y[~sig], s=6, c="#B0B0B0", alpha=0.5, lw=0, label="NS")
    ax.scatter(x[sig], y[sig], s=8, c="#0279EE", alpha=0.7, lw=0, label="FDR<0.05")
    lab = {"nemA": "#D55E00", "nemR": "#D55E00", "yqhD": "#D55E00", "dkgA": "#D55E00",
           "gloA": "#D55E00", "ahpC": "#009E73", "ahpF": "#009E73", "katG": "#009E73",
           "grxA": "#009E73", "iscR": "#CC79A7", "iscS": "#CC79A7", "iscU": "#CC79A7",
           "iscA": "#CC79A7", "hyaA": "#0072B2"}
    texts = []
    for _, r in dev.iterrows():
        if r["symbol"] in lab:
            texts.append(ax.text(r.logFC, -np.log10(max(r["adj.P.Val"], 1e-10)), r["symbol"],
                                 fontsize=7.5, color=lab[r["symbol"]], weight="bold"))
    adjust_text(texts, ax=ax, arrowprops=dict(arrowstyle="-", lw=0.5, color="gray", alpha=0.6),
                expand=(1.3, 1.6), force_text=(0.4, 0.6))
    ax.axhline(-np.log10(0.05), ls="--", lw=0.8, c="k", alpha=0.4)
    ax.set_xlabel("log2 fold change (reuterin / control)")
    ax.set_ylabel("-log10(FDR)")
    ax.set_title("A  Reuterin transcriptome (GSE19760, E. coli DH5$\\alpha$, n=5)",
                 loc="left", fontsize=10)
    ax.legend(frameon=False, fontsize=8, loc="center left")
    ax.set_xlim(-4.8, 7.0); ax.set_ylim(-0.15, 3.6)

    ax = axes[1]
    a = dev.AveExpr.values
    ax.scatter(a[~sig], x[~sig], s=6, c="#B0B0B0", alpha=0.5, lw=0, label="NS")
    ax.scatter(a[sig], x[sig], s=8, c="#0279EE", alpha=0.7, lw=0, label="FDR<0.05")
    texts = []
    for _, r in dev.iterrows():
        if r["symbol"] in lab:
            texts.append(ax.text(r.AveExpr, r.logFC, r["symbol"], fontsize=7.5,
                                 color=lab[r["symbol"]], weight="bold"))
    adjust_text(texts, ax=ax, arrowprops=dict(arrowstyle="-", lw=0.5, color="gray", alpha=0.6),
                expand=(1.3, 1.6), force_text=(0.4, 0.6))
    ax.axhline(0, c="k", lw=0.6, alpha=0.5)
    ax.set_xlabel("Mean log2 intensity (A)"); ax.set_ylabel("log2 fold change (M)")
    ax.set_title("B  MA plot", loc="left", fontsize=10)
    ax.set_ylim(-4.8, 7.0)

    ax = axes[2]
    ss = uni[uni.contrast == "Reuterin"].sort_values("raw_mean_logFC")
    labels = {"ISC operon": "iscRSUA-hscBA-fdx (Fe-S biogenesis)",
              "SUF operon": "sufABCDSE (Fe-S, stress)",
              "RyhB targets": "RyhB classic targets",
              "Fur iron uptake": "Fur iron-uptake regulon",
              "OxyR regulon": "OxyR regulon",
              "Cysteine regulon": "Cys sulfur-assimilation regulon",
              "Glutathione/glyoxalase": "GSH / glyoxalase system",
              "Electrophile detoxification": "Electrophile detoxification"}
    colors = ["#D55E00" if q < 0.01 else ("#E69F00" if q < 0.05 else "#B0B0B0")
              for q in ss.roast_q_up]
    ax.barh(range(len(ss)), ss.raw_mean_logFC, color=colors, height=0.65)
    ax.set_yticks(range(len(ss)))
    ax.set_yticklabels([f"{labels[s]}  (n={n})" for s, n in zip(ss.gene_set, ss.n_genes)], fontsize=8.5)
    for i, (v, q) in enumerate(zip(ss.raw_mean_logFC, ss.roast_q_up)):
        star = stars_q(q) if stars_q(q) else "ns"
        ax.text(v + (0.06 if v >= 0 else -0.06), i, star, va="center",
                ha="left" if v >= 0 else "right", fontsize=9)
    ax.axvline(0, c="k", lw=0.8)
    ax.set_xlabel("Mean log2FC of gene set (roast-tested genes only; n given)")
    ax.set_title("C  Gene-set response (roast test)", loc="left", fontsize=10)
    ax.set_xlim(-0.4, 3.4)
    plt.tight_layout()
    save(fig, "Fig1_reuterin_program_v4")

    # =====================================================================
    # FIGURE 2 v4: operon bars + replicate heatmap + RyhB targets + operon track
    # =====================================================================
    fig = plt.figure(figsize=(16.5, 4.9))
    gs = fig.add_gridspec(1, 4, width_ratios=[1.0, 1.25, 1.0, 1.35], wspace=0.52)

    ax = fig.add_subplot(gs[0])
    operon = GENE_SETS["ISC operon"]
    sub = de.set_index("symbol").loc[operon]
    ax.bar(range(len(sub)), sub.logFC, color="#CC79A7", width=0.7)
    for i, (v, p) in enumerate(zip(sub.logFC, sub["adj.P.Val"])):
        star = "**" if p < 0.01 else ("*" if p < 0.05 else "")
        ax.text(i, v + 0.08, star, ha="center", fontsize=10)
    ax.set_xticks(range(len(sub)))
    ax.set_xticklabels(operon, rotation=45, ha="right", fontsize=9, style="italic")
    ax.set_ylabel("log2FC"); ax.set_ylim(0, 2.4)
    ax.set_title("A  iscRSUA-hscBA-fdx operon (Fe-S biogenesis)", loc="left", fontsize=10)
    ax.axhline(0, c="k", lw=0.8)

    ax = fig.add_subplot(gs[1])
    axis_genes = ["iscR", "iscS", "iscU", "iscA", "hscB", "hscA", "fdx", "sufA", "sufB", "sufC",
                  "sufD", "sufS", "sufE", "nemA", "nemR", "yqhD", "yqhC", "dkgA", "dkgB",
                  "ahpC", "ahpF", "katG", "grxA", "trxC", "gor"]
    axis_genes = [g for g in axis_genes if g in M.index]
    Hm = M.loc[axis_genes]
    im = ax.imshow(Hm.values, aspect="auto", cmap="RdBu_r", vmin=-3, vmax=3)
    ax.set_xticks(range(5)); ax.set_xticklabels([f"R{i}" for i in range(1, 6)], fontsize=9)
    ax.set_yticks(range(len(Hm)))
    ax.set_yticklabels(Hm.index, fontsize=8.5, style="italic")
    plt.colorbar(im, ax=ax, shrink=0.8, label="log2FC")
    ax.set_title("B  Sulfur-metabolism & oxidative-stress genes per replicate", loc="left",
                 fontsize=10)

    ax = fig.add_subplot(gs[2])
    ryhb = ["sodB", "fumA", "acnA", "sdhA", "sdhB", "sdhC", "sdhD", "bfr", "ftnA"]
    sub2 = de.set_index("symbol").loc[ryhb]
    ax.bar(range(len(sub2)), sub2.logFC, color="#7A7A7A", width=0.7)
    ax.set_xticks(range(len(sub2)))
    ax.set_xticklabels(ryhb, rotation=45, ha="right", fontsize=9, style="italic")
    ax.set_ylabel("log2FC"); ax.set_ylim(-1.6, 1.6)
    ax.axhline(0, c="k", lw=0.8)
    ax.set_title("C  RyhB classic targets (no degradation signature)", loc="left", fontsize=10)

    ax = fig.add_subplot(gs[3])
    coord = ft[(ft["feature"] == "gene") & ft.symbol.isin(operon)][
        ["symbol", "start", "end", "strand"]].set_index("symbol")
    x0 = coord.loc["fdx", "start"] - 400
    x1 = coord.loc["iscR", "end"] + 400
    ax.axhline(0, c="k", lw=1.2)
    cmap = plt.cm.Reds
    norm = plt.Normalize(0, 2.2)
    for k, g in enumerate(operon):  # minus strand: transcription right-to-left
        s, e = coord.loc[g, "start"], coord.loc[g, "end"]
        fc = float(de.set_index("symbol").loc[g, "logFC"])
        ax.add_patch(plt.Rectangle((s, -0.32), e - s, 0.64, facecolor=cmap(norm(fc)),
                                   edgecolor="k", lw=0.7, zorder=3))
        y_lab = 0.52 if k % 2 == 0 else 0.86
        ax.text((s + e) / 2, y_lab, g, ha="center", fontsize=8.5, style="italic")
    iscs_end = coord.loc["iscS", "end"]
    ax.add_patch(plt.Rectangle((iscs_end + 2, -0.32), 18, 0.96, facecolor="#0279EE",
                               edgecolor="none", zorder=4, alpha=0.95))
    ax.annotate("RyhB pairing site", xy=(iscs_end + 11, 0.68), xytext=(iscs_end - 700, 1.12),
                fontsize=8, color="#0279EE", ha="center",
                arrowprops=dict(arrowstyle="-", color="#0279EE", lw=0.9))
    ax.text(x1 - 60, -0.95, "transcription", fontsize=7.5, color="k", ha="right", style="italic")
    ax.annotate("", xy=(x0 + 900, -0.78), xytext=(x1 - 60, -0.78),
                arrowprops=dict(arrowstyle="-|>", color="k", lw=0.9))
    ax.set_xlim(x0, x1); ax.set_ylim(-1.30, 1.45)
    ax.axis("off")
    sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    cb = plt.colorbar(sm, ax=ax, shrink=0.55, pad=0.01, orientation="horizontal", location="bottom")
    cb.set_label("log2FC", fontsize=8); cb.ax.tick_params(labelsize=7.5)
    ax.set_title("D  Operon organization (MG1655)", loc="left", fontsize=10)
    save(fig, "Fig2_isc_operon_v4")

    # =====================================================================
    # FIGURE 3 v4: tiered network + coverage + forest + chimera/MFE
    # (Table S1 content is numerically unchanged from v3 -- same 52 CLASH edges;
    #  only source-row provenance was added -- so this panel reproduces v3
    #  exactly, now read from the v4-named, version-consistent file.)
    # =====================================================================
    edges = t1.copy()

    def edge_tier(r):
        if r.in_RILseq == "Yes" or r.total_hybrids >= 5:
            return "high"
        if r.total_hybrids >= 2:
            return "standard"
        return "exploratory"

    edges["tier"] = edges.apply(edge_tier, axis=1)
    TIER_STYLE = {"high": dict(color="#0279EE", alpha=0.95, ls="-", zorder=3),
                  "standard": dict(color="#56B4E9", alpha=0.8, ls="-", zorder=2),
                  "exploratory": dict(color="#ABABAB", alpha=0.5, ls=(0, (3, 2)), zorder=1)}
    TIER_LW = {"high": 2.6, "standard": 1.5, "exploratory": 0.8}

    fig = plt.figure(figsize=(15.5, 11.5))
    gs = fig.add_gridspec(2, 2, height_ratios=[1.55, 1], width_ratios=[1.5, 1],
                          hspace=0.46, wspace=0.18)

    ax = fig.add_subplot(gs[0, 0])
    srna_order = edges.groupby("sRNA").total_hybrids.sum().sort_values(ascending=False).index.tolist()
    target_order = []
    for p in pathway_colors:
        target_order += sorted(set(edges[edges.mRNA.isin(sulfur_genes[p])].mRNA))
    primary = edges.loc[edges.groupby("mRNA").total_hybrids.idxmax(), ["mRNA", "sRNA"]]
    t2s = dict(zip(primary.mRNA, primary.sRNA))
    srank = {s: i for i, s in enumerate(srna_order)}
    target_order = sorted(target_order,
                          key=lambda t: (srank.get(t2s.get(t, ""), 99),
                                         list(pathway_colors).index(
                                             [k for k, v in sulfur_genes.items() if t in v][0]), t))
    sy = {s: -i * 1.9 for i, s in enumerate(srna_order)}
    ty = {t: -i * 0.82 for i, t in enumerate(target_order)}
    off = (len(target_order) * 0.82 - len(srna_order) * 1.9) / 2
    sy = {s: yy - off for s, yy in sy.items()}
    sx, tx = 0.0, 1.0
    for tiername in ["exploratory", "standard", "high"]:  # draw high last (on top)
        for _, r in edges[edges.tier == tiername].iterrows():
            s, t = r.sRNA, r.mRNA
            st = TIER_STYLE[tiername]
            ax.plot([sx, tx], [sy[s], ty[t]], ls=st["ls"], lw=TIER_LW[tiername],
                    color=st["color"], alpha=st["alpha"], zorder=st["zorder"],
                    solid_capstyle="round")
    ax.scatter([sx] * len(sy), list(sy.values()), s=300, color="#E9ED4C", edgecolor="k", zorder=4)
    for s, yy in sy.items():
        ax.text(sx - 0.03, yy, s, ha="right", va="center", fontsize=10.5, fontweight="bold",
                style="italic")
    for t, yy in ty.items():
        p = [k for k, v in sulfur_genes.items() if t in v][0]
        ax.scatter([tx], [yy], s=110, color=pathway_colors[p], edgecolor="k", zorder=4)
        ax.text(tx + 0.03, yy, t, ha="left", va="center", fontsize=9, style="italic")
    # highlight the lead candidate edge ArcZ-cysB
    mx, my = 0.5, (sy["arcZ"] + ty["cysB"]) / 2
    ax.annotate("ArcZ–cysB\n(lead candidate)", xy=(mx, my), xytext=(0.40, my + 3.4),
                fontsize=8.5, color="#0279EE", ha="center", fontweight="bold",
                arrowprops=dict(arrowstyle="-|>", color="#0279EE", lw=1.0))
    ax.set_xlim(-0.32, 1.30); ax.set_ylim(min(ty.values()) - 3.4, my + 5.6)
    ax.axis("off")
    ax.set_title("A  Candidate sRNA–sulfur network (Hfq CLASH, evidence-tiered)", loc="left",
                 fontsize=12, fontweight="bold")
    edge_legend = [Line2D([0], [0], color=TIER_STYLE["high"]["color"], lw=2.6,
                          label="high (RIL-seq or ≥5 chimeras)"),
                   Line2D([0], [0], color=TIER_STYLE["standard"]["color"], lw=1.5,
                          label="standard (2–4 chimeras)"),
                   Line2D([0], [0], color=TIER_STYLE["exploratory"]["color"], lw=0.9,
                          ls=(0, (3, 2)), alpha=0.7, label="exploratory (single chimera)")]
    ax.legend(handles=edge_legend, loc="upper left", fontsize=9, frameon=False,
              bbox_to_anchor=(-0.02, -0.04), title="Evidence tier", title_fontsize=9.5)

    axb = fig.add_subplot(gs[0, 1])
    hubs = edges.groupby("sRNA").size().sort_values(ascending=False).index.tolist()[:9]
    bottoms = np.zeros(len(hubs))
    for p in pathway_colors:
        vals = [len(set(edges[(edges.sRNA == h) & (edges.mRNA.isin(sulfur_genes[p]))].mRNA))
                for h in hubs]
        if sum(vals) > 0:
            axb.bar(hubs, vals, bottom=bottoms, color=pathway_colors[p], edgecolor="white",
                    label=pathway_labels[p], width=0.65)
            bottoms += np.array(vals)
    axb.set_ylabel("Sulfur-network target genes", fontsize=11)
    axb.set_title("B  Sulfur-network coverage per sRNA", loc="left", fontsize=12,
                  fontweight="bold")
    axb.tick_params(axis="x", rotation=45)
    for tick in axb.get_xticklabels():
        tick.set_fontstyle("italic")
    axb.spines[["top", "right"]].set_visible(False)
    axb.legend(fontsize=8.5, frameon=False, loc="upper right", title="Target functional category",
               title_fontsize=9)

    # (C) forest plot: Fisher OR per pathway (primary analysis; same 4400/1074
    # background as Table S5 "Primary" rows -- recomputed directly from Table S1
    # so panel and table cannot silently drift apart)
    axc = fig.add_subplot(gs[1, 0])
    N_GENOME = 4400
    N_CLASH = 1074
    rows = []
    tot_a = len(set(edges.mRNA))
    tot_s = len(set(g for gs_ in sulfur_genes.values() for g in gs_))
    rows.append(("All sulfur axis (86 genes)", tot_a, tot_s, True))
    fes_genes = sulfur_genes["iscRSUA_operon"] + sulfur_genes["suf_operon"] + sulfur_genes["FeS_iron"]
    fes_a = len(set(edges[edges.mRNA.isin(fes_genes)].mRNA))
    rows.append(("Fe-S/iron subsystem (29 genes)", fes_a, len(fes_genes), True))
    for p in pathway_colors:
        a = len(set(edges[edges.mRNA.isin(sulfur_genes[p])].mRNA))
        rows.append((pathway_labels[p], a, len(sulfur_genes[p]), False))
    ors = []
    for name, a, size, robust in rows:
        b = size - a
        c = N_CLASH - a
        d = N_GENOME - size - c
        od, pv = fisher_exact([[a, b], [c, d]])
        se = np.sqrt(1 / max(a, .5) + 1 / max(b, .5) + 1 / max(c, .5) + 1 / max(d, .5))
        lo, hi = np.exp(np.log(od) - 1.96 * se), np.exp(np.log(od) + 1.96 * se)
        ors.append((name, od, lo, hi, pv, a, size, robust))
    ypos = np.arange(len(ors))[::-1]
    for yy, (name, od, lo, hi, pv, a, size, robust) in zip(ypos, ors):
        col = "#D55E00" if pv < 0.05 else "#7A7A7A"
        axc.plot([lo, hi], [yy, yy], color=col, lw=1.6)
        axc.scatter([od], [yy], s=55, color=col, zorder=3, edgecolor="k", linewidth=0.5,
                    marker="o" if robust else "o", facecolor=col if robust else "white")
        star = "***" if pv < 0.001 else ("**" if pv < 0.01 else ("*" if pv < 0.05 else ""))
        axc.text(hi * 1.12, yy, f"OR={od:.2f} ({a}/{size}){star}", va="center", fontsize=8.2)
    axc.axvline(1, c="k", lw=0.9, ls="--")
    axc.set_yticks(ypos)
    axc.set_yticklabels([r[0] for r in ors], fontsize=9)
    axc.set_xscale("log")
    axc.set_xlim(0.35, 200)
    axc.set_xticks([0.5, 1, 2, 4, 8, 16, 32])
    axc.set_xticklabels(["0.5", "1", "2", "4", "8", "16", "32"])
    axc.set_xlabel("Odds ratio among CLASH targets (95% CI)", fontsize=10)
    axc.set_title("C  Enrichment of sulfur-network genes in the CLASH interactome", loc="left",
                  fontsize=12, fontweight="bold")
    axc.spines[["top", "right"]].set_visible(False)
    axc.scatter([], [], s=55, facecolor="#7A7A7A", edgecolor="k",
                label="robust to expression-background restriction")
    axc.scatter([], [], s=55, facecolor="white", edgecolor="k", label="primary analysis only")
    axc.legend(fontsize=8, frameon=False, loc="upper center", bbox_to_anchor=(0.5, -0.24),
               ncol=2)

    # (D) chimera count vs MFE, colored by evidence tier
    axd = fig.add_subplot(gs[1, 1])
    for tiername in ["exploratory", "standard", "high"]:
        sub = edges[edges.tier == tiername]
        st = TIER_STYLE[tiername]
        axd.scatter(sub.best_MFE, sub.total_hybrids, s=42 if tiername != "high" else 56,
                    color=st["color"], edgecolor="k", linewidth=0.4, alpha=0.9,
                    label={"high": "high (RIL-seq or ≥5)", "standard": "standard (2–4)",
                           "exploratory": "exploratory (1)"}[tiername],
                    zorder=st["zorder"])
    texts = []
    for _, r in edges.nlargest(5, "total_hybrids").iterrows():
        texts.append(axd.text(r.best_MFE, r.total_hybrids, f"{r.sRNA}–{r.mRNA}",
                              fontsize=8, style="italic"))
    adjust_text(texts, ax=axd, arrowprops=dict(arrowstyle="-", color="#666666", lw=0.6),
                expand=(1.5, 2.0), force_text=(0.5, 0.7))
    axd.set_yscale("log")
    axd.set_xlabel("Best predicted duplex MFE (kcal/mol)", fontsize=10)
    axd.set_ylabel("Chimeric reads (log scale)", fontsize=10)
    axd.set_title("D  Interaction strength vs predicted duplex stability", loc="left",
                  fontsize=12, fontweight="bold")
    axd.legend(fontsize=9, frameon=False, loc="upper right", title="Evidence tier",
               title_fontsize=9)
    axd.spines[["top", "right"]].set_visible(False)
    save(fig, "Fig3_candidate_network_v4")

    # =====================================================================
    # FIGURE 4 v4: heatmap (raw mean log2FC, roast stars) + scatter + dumbbell
    # Now sourced entirely from the v4 statistics engine: DE_HOCl/DE_Ferrate/DE_Hpx
    # (TMM+voom primary model) and genesets_primary.csv (Hpx OxyR score now
    # correctly excludes ahpC/katG; ISC/SUF gene sets reported at roast-tested n).
    # =====================================================================
    fc_reu = de.dropna(subset=["symbol", "logFC"]).groupby("symbol").logFC.mean()

    def load_fc(f):
        d = pd.read_csv(f"{STATS}/{f}")
        d = d.dropna(subset=["symbol", "logFC"])
        return d.groupby("symbol").logFC.mean()

    contrasts = {
        "Reuterin": fc_reu,
        "Hpx": load_fc("DE_Hpx.csv"),
        "HOCl": load_fc("DE_HOCl.csv"),
        "Ferrate": load_fc("DE_Ferrate.csv"),
    }
    piv = uni.pivot(index="gene_set", columns="contrast", values="raw_mean_logFC")[CONTRASTS]
    piv_q = uni.pivot(index="gene_set", columns="contrast", values="roast_q_up")[CONTRASTS]
    order = piv["Reuterin"].sort_values(ascending=False).index
    piv = piv.loc[order]; piv_q = piv_q.loc[order]

    fig = plt.figure(figsize=(17.5, 5.6))
    gs = fig.add_gridspec(1, 3, width_ratios=[1.12, 1.0, 1.25], wspace=0.38)

    ax = fig.add_subplot(gs[0])
    vmax = 3.0
    im = ax.imshow(piv.values, cmap="RdBu_r", vmin=-vmax, vmax=vmax, aspect="auto")
    ax.set_xticks(range(4))
    ax.set_xticklabels(["Reuterin\n(GSE19760)", "Hpx$^-$ H$_2$O$_2$\n(GSE165009)",
                        "HOCl\n(GSE126176)", "Ferrate\n(GSE126176)"], fontsize=8.5,
                       rotation=24, ha="right")
    ax.set_yticks(range(len(piv.index)))
    ax.set_yticklabels(piv.index, fontsize=9.5)
    for i in range(len(piv.index)):
        for j in range(4):
            v = piv.values[i, j]; q = piv_q.values[i, j]
            ax.text(j, i, f"{v:+.2f}{stars_q(q)}", ha="center", va="center", fontsize=8.2,
                    color="white" if abs(v) > 2.0 else "black")
    ax.set_title("A  Gene-set response across four stresses", loc="left", fontsize=11,
                 fontweight="bold")
    cb = plt.colorbar(im, ax=ax, shrink=0.75, pad=0.02)
    cb.set_label("mean log$_2$FC (array: loess; RNA-seq: TMM+voom)", fontsize=8.5)

    axb = fig.add_subplot(gs[1])
    fc_hpx = contrasts["Hpx"]
    common = fc_reu.index.intersection(fc_hpx.index)
    xx, yy2 = fc_reu[common], fc_hpx[common]
    HPX_DELETED = {"katG", "ahpC", "katE"}  # excluded from Hpx gene-set scoring (genotype: DeltakatE DeltakatG DeltaahpC)
    axb.scatter(xx, yy2, s=6, color="#BBBBBB", alpha=0.5, linewidths=0)
    GENE_SETS4 = {"ISC operon": (GENE_SETS["ISC operon"], "#D55E00", "o"),
                  "SUF operon": (GENE_SETS["SUF operon"], "#E69F00", "s"),
                  "Electrophile detoxification": (GENE_SETS["Electrophile detoxification"], "#CC79A7", "^"),
                  "Cysteine regulon": (GENE_SETS["Cysteine regulon"], "#009E73", "D")}
    sxv, syv = [], []
    for gsname, (glist, c, mk) in GENE_SETS4.items():
        g = [z for z in glist if z in common and z not in HPX_DELETED]
        sxv.extend(xx[g].values); syv.extend(yy2[g].values)
        axb.scatter(xx[g], yy2[g], s=42, color=c, marker=mk, label=gsname, edgecolor="k",
                    linewidth=0.4, zorder=3)
    texts = []
    for g in ["iscS", "iscU", "iscA", "iscR", "sufA", "sufB", "nemA", "yqhD", "cysJ", "cysI"]:
        if g in common:
            texts.append(axb.text(xx[g], yy2[g], g, fontsize=8.5, style="italic"))
    adjust_text(texts, x=np.array(sxv), y=np.array(syv), ax=axb,
                arrowprops=dict(arrowstyle="-", color="#666666", lw=0.6),
                expand=(2.0, 2.8), force_text=(0.9, 1.3), force_static=(0.4, 0.6))
    axb.axhline(0, color="k", lw=0.5); axb.axvline(0, color="k", lw=0.5)
    axb.set_xlabel("Reuterin log$_2$FC (GSE19760)", fontsize=10)
    axb.set_ylabel("Hpx$^-$ H$_2$O$_2$ log$_2$FC (GSE165009)", fontsize=10)
    axb.set_title("B  Reuterin vs endogenous peroxide stress", loc="left", fontsize=11,
                  fontweight="bold")
    axb.legend(fontsize=8, frameon=False, loc="lower right")
    axb.spines[["top", "right"]].set_visible(False)

    axc = fig.add_subplot(gs[2])
    isc = GENE_SETS["ISC operon"]; suf = GENE_SETS["SUF operon"]
    glist = isc + suf
    ypos = np.arange(len(glist))[::-1]
    cmap4 = ["#D55E00", "#0072B2", "#56B4E9", "#009E73"]
    clab = ["Reuterin", "Hpx$^-$ H$_2$O$_2$", "HOCl", "Ferrate"]
    for yy3, g in zip(ypos, glist):
        vals = [contrasts[c].get(g, np.nan) for c in CONTRASTS]
        axc.plot([np.nanmin(vals) - 0.15, np.nanmax(vals) + 0.15], [yy3, yy3],
                 color="#DDDDDD", lw=1.4, zorder=1)
        for v, c4 in zip(vals, cmap4):
            if not np.isnan(v):
                axc.scatter([v], [yy3], s=52, color=c4, edgecolor="k", linewidth=0.4, zorder=3)
    axc.axvline(0, c="k", lw=0.8)
    axc.set_yticks(ypos)
    axc.set_yticklabels(glist, fontsize=9, style="italic")
    for i, g in enumerate(glist):
        if g in suf:
            axc.get_yticklabels()[i].set_color("#7A4E00")
    axc.set_xlabel("log$_2$FC per contrast", fontsize=10)
    axc.set_title("C  ISC vs SUF operon members across stresses", loc="left", fontsize=11,
                  fontweight="bold")
    handles = [Line2D([0], [0], marker="o", color="w", markerfacecolor=c, markeredgecolor="k",
                      markersize=8, label=l) for c, l in zip(cmap4, clab)]
    axc.legend(handles=handles, fontsize=8.5, frameon=False, loc="upper center",
               bbox_to_anchor=(0.5, -0.16), ncol=4)
    axc.spines[["top", "right"]].set_visible(False)
    axc.set_xlim(-3.2, 4.4)
    save(fig, "Fig4_crossstress_v4")

if __name__ == "__main__":
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--stats", required=True, help="recompute_statistics.R output directory")
    p.add_argument("--final", required=True, help="build_tables.py --out directory (for supplementary/Table_S1)")
    p.add_argument("--data", required=True, help="raw data directory (for mg1655_feature_table.txt.gz)")
    p.add_argument("--fig-out", required=True, help="directory to write Fig1-4 .png/.svg (Fig5 written by make_fig5_conservation.py)")
    a = p.parse_args()
    main(a.stats, a.final, a.data, a.fig_out)
    print("FIGURES 1-4 DONE")
